version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: ken
      MYSQL_PASSWORD: ken
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
  selenium:
    image: selenium/standalone-chromium:133.0
    restart: always
    ports:
      - "4444:4444"
      - "7900:7900"

volumes:
  mysql_data:
