version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: ken
      MYSQL_PASSWORD: ken
    ports:
      - "3306:3306"
