spring:
  datasource:
    url: jdbc:mysql://db.webcrawlerapi.orb.local:3306/webcrawler
    username: ken
    password: ken

ptt:
  crawler:
    index:
      url: https://www.ptt.cc/bbs/index.html

webdriver:
  path: http://selenium.webcrawlerapi.orb.local:4444/wd/hub
