spring:
  datasource:
    url: jdbc:mysql://mysql-svc:3306/webcrawler
    username: root
    password: root
ptt:
  crawler:
    index:
      url: https://www.ptt.cc/bbs/index.html
webdriver:
  path: http://selenium-svc:4444/wd/hub
