spring:
  application:
    name: webcrawlerapi
  datasource:
    url: jdbc:mysql://localhost:3330/webcrawler
    username: root
    password: HKtv2014
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

ig:
  crawler:
    login: "https://www.instagram.com/"
    use:
      account: "<your-ig-account>"
      password: "<your-ig-password>"

ptt:
  crawler:
    index:
      url: https://www.ptt.cc/bbs/index.html

