spring:
  application:
    name: webcrawlerapi
  datasource:
    url: jdbc:mysql://mysql.default.svc.cluster.local:3306/webcrawler
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

ptt:
  crawler:
    index:
      url: https://www.ptt.cc/bbs/index.html
